config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :admin do
    get '/' => 'admin#index'
  end

  root to: 'application#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  has_many :users
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true, on: :create
  validates :last_name, presence: true, on: :create
  validates :phone, presence: true, on: :create
  validates :birth_date, presence: true, on: :create

  belongs_to :address

  has_and_belongs_to_many :roles

  def admin?
    self.roles.include? Role.find_by_name('admin')
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :verify_admin

  # GET /admin
  def index
    puts 'in admin controller'
  end

  private

  def verify_admin
    unless current_user.admin?
      flash.alert 'You do not have access to this page'
      redirect_to :root
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  # GET /
  def index

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def new
    @address = Address.new
    super
  end

  def create
    p = permit_address_params(params)
    f = consistent_address_fields(p)

    super { |u|
      u.address =  Address.find_or_create_by(f)
    }
  end

  def edit
    @address = current_user.address.present? ? current_user.address : Address.new
    super
  end

  def update
    p = permit_address_params(params)
    f = consistent_address_fields(p)
    current_user.address = Address.find_or_create_by(f)

    current_user.save

    super
  end

  protected

  def consistent_address_fields(params)
    new_params = {}

    params.each { |k, v|
      if v.blank?
        new_params[k] = nil
      else
        case k
          # Use strings here, not :symbols, or it will ruin your day
          when 'address1', 'address2', 'city'
            new_params[k] = v.title_case
          when 'state'
            new_params[k] = v.upcase.strip
          else
            new_params[k] = v.strip
        end
      end
    }

    new_params
  end

  def permit_address_params(params)
    params[:address].permit([:address1, :address2, :city, :state, :zip])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        << :first_name << :last_name << :email << :phone << :birth_date
    devise_parameter_sanitizer.for(:account_update) << :first_name << :last_name << :email << :phone << :birth_date
  end
end

class String
  def title_case
    title = self.split
    title.map do |word|
      word.capitalize
    end.join(" ")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admin/index.html.erb
<h2>Admin page</h2>

Some text

app/views/application/index.html.erb
homepage for application

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GecYouth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'partials/header' %>

<%= yield %>

</body>
</html>

app/views/partials/_header.html.erb
<p class='navbar-text pull-right'>
  <%= link_to 'Home', root_path, class: 'navbar-link' %>
  <% if user_signed_in? %>
      <strong><%= current_user.email %></strong>
      <% if current_user.admin? %>
          <%= link_to 'Admin', admin_path, class: 'navbar-link' %>
      <% end %>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to 'Login', new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>


<% if notice %>
    <p class='alert alert-success'><%= notice %></p>
<% end %>
<% if alert %>
    <p class='alert alert-danger'><%= alert %></p>
<% end %>